name: SMC Sentinela Monitor 24h
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install pandas requests yfinance matplotlib
      - name: Run
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
        run: python teste_conexao.py
